### ISSUE TITLE
Gleiche Texte bei unterschiedlichen fällen

### ISSUE THREAD

**Issue by chhaben** [adiehl/hdgdldsgvo#11]
Der Text bei "Beschwerde Aufsichtsbehörde" ist der selbe wie bei "Antrag auf Einschränkung".
Da ist nur ein "ACHTUNG!!" davor

**Comment by adiehl** [comment]
Danke, das war ein Copy-Paste fehler, die Vorlage "Beschwerde bei Aufsichtsbehörde" ist noch in Arbeit und kommt bald.
Wurde im Code und in der Published Site entfernt
